Add Contrasts and Scheme pages
contember/docs pull request #52
Opened 2022-04-19 07:22 UTC by attitude

2022-04-19 10:54 UTC, jonasNobile requested changes

2022-04-19 10:54 UTC, jonasNobile commented on src/theming/Luminance/Chart.tsx
> +  .reverse();
```suggestion
const COLORS_RANGE = Array.from({length: COLORS_COUNT}, (_, index) => index).reverse()
```

2022-04-19 10:54 UTC, jonasNobile commented on src/theming/Luminance/Chart.tsx
> +  .reverse();
```suggestion
const range = Array.from({length: count}, (_, index) => index).reverse()
```

2022-04-19 10:54 UTC, jonasNobile commented on src/theming/Luminance/Chart.tsx
> +        {"\n"}
```suggestion
        <br/>
```

2022-04-19 10:54 UTC, jonasNobile commented on src/theming/Luminance/Chart.tsx
> +        {"\n"}
```suggestion
        <br />
```

2022-04-19 20:58 UTC, jonasNobile commented on src/theming/Helpers/rangeOfNumbers.ts
> +export function rangeOfNumbers (start: number, end: number, step: number = 1) {
```suggestion
export function rangeOfNumbers(start: number, end: number, step: number = 1) {
```

2022-04-20 14:23 UTC, VojtaStanek commented
The `rangeOfNumbers` func is:
a) too complicated
b) wrong (eg. why round?)

2022-04-21 15:01 UTC, attitude commented
@VojtaStanek, `rangeOfNumbers()` does suit its needs. I refactored the code to be more readable and fixed use of `Math.round()` to `Math.floor()` method and confirmed it is working. Can you be now more specific about your concerns?

(Please note, there is only a slight change this method would be use otherwise as internal for the docs.)

Thanks

2022-04-22 09:30 UTC, VojtaStanek commented
Looks ok now.

2022-04-22 10:49 UTC, jonasNobile requested changes
> Reviewed 28 of 28 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/docs/52)* status: all files reviewed, 1 unresolved discussion (waiting on @attitude)

___
*[src/theming/Helpers/cssToSASS.ts, line 2 at r1](https://reviewable.io/reviews/contember/docs/52#-N0Fqsj3D6gidb9LYyqA:-N0Fqsj4-XVcyOBariwF:bz916y2) ([raw file](https://github.com/contember/docs/blob/b41d84d8cfbc9c0f28071672ddcc2f42f6961d3d/src/theming/Helpers/cssToSASS.ts#L2)):*
> ```XML
> export function cssToSASS(css: string) {
>   return css.replace(/;/g, "").replace(/\{/g, "").replace(/\}/g, "").trim()
> ```

OR

```ts
css.replaceAll(";", "").replaceAll("{", "").replaceAll("}", "").trim()
```



_Suggestion:_
```XML
  return css.replace(/[;{}]/g, "").trim()
```


<!-- Sent from Reviewable.io -->

2022-04-22 11:13 UTC, attitude reviewed
> *[Reviewable](https://reviewable.io/reviews/contember/docs/52)* status: 5 of 28 files reviewed, 1 unresolved discussion (waiting on @jonasNobile)

___
*[src/theming/Helpers/cssToSASS.ts, line 2 at r1](https://reviewable.io/reviews/contember/docs/52#-N0Fqsj3D6gidb9LYyqA:-N0FxuYh8WkafLsW17s2:b-896fix) ([raw file](https://github.com/contember/docs/blob/b41d84d8cfbc9c0f28071672ddcc2f42f6961d3d/src/theming/Helpers/cssToSASS.ts#L2)):*
<details><summary><i>Previously, jonasNobile (Jonáš Nobile) wrote…</i></summary><blockquote>

OR

```ts
css.replaceAll(";", "").replaceAll("{", "").replaceAll("}", "").trim()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 11:12 UTC, jonasNobile approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/contember/docs/52)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @attitude)



<!-- Sent from Reviewable.io -->

2022-04-27 11:12 UTC, merged